apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vpa
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: vertical-pod-autoscaler
      sourceRef:
        kind: HelmRepository
        name: cowboysysop
        namespace: monitoring
      interval: 1h
  timeout: 3m
  values:
    admissionController:
      enabled: true
    updater:
      enabled: true
    recommender:
      enabled: true
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: tempo
  namespace: monitoring
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: tempo
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
      - containerName: tempo
        minAllowed:
          cpu: 100m
          memory: 256Mi
        maxAllowed:
          cpu: 1000m
          memory: 2Gi
