---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: merge-conflict-survivors
  namespace: flux-system
spec:
  image: 937697200280.dkr.ecr.eu-west-1.amazonaws.com/merge-conflict-survivors
  interval: 1m

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: merge-conflict-survivors
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: merge-conflict-survivors
  policy:
    semver:
      range: '*'

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: merge-conflict-survivors
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: flux@example.com
        name: Flux
      messageTemplate: 'chore: update image to {{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  update:
    path: ./k8s/deployment.yaml
    strategy: Setters
