apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- hpa.yaml
- service.yaml
- karpenter-helmrepo.yaml
- karpenter-release.yaml
- karpenter-provisioner.yaml

images:
- name: app-image
  newName: 937697200280.dkr.ecr.eu-west-1.amazonaws.com/merge-conflict-survivors
  newTag: 259e016b619643ab7a9a322570cc17f52bbc8096
