apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: website
  labels:
    app: website
spec:
  type: LoadBalancer
  selector:
    app: website
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
